name: equistera-inference
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision=0.16.0
  - pip
  - pip:
    - openmim
    - mmengine==0.10.3
    - mmcv==2.1.0
    - mmdet==3.3.0
    - mmpose==1.3.1
    - opencv-python
    - matplotlib
    - scipy
    - json_tricks
    - pycocotools
